spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/SIEBELDB
    username: SIEBEL
    password: SIEBEL
    driverClassName: oracle.jdbc.OracleDriver
    type: oracle.jdbc.pool.OracleDataSource